### PR TITLE
refactor(build): one sbt def to rule them all

### PR DESCRIPTION
**Pull request by datYori**
We group all components in a single sbt build definition.

This is a beta ugly version with some code duplication.

Incoming:
- dynamic license header handling
- annotation processor as a generic plugin
- grammar and lexer generation as plugin
- better antl4 and truffle-processor jar management

internal ref RD-10838

### CODE REVIEW

**Review by Dimitris-Mil — APPROVED** [review]
ci lgtm

**Review by bgaidioz — APPROVED** [review]

**Pull request merged**
