### PR TITLE
RD-9312 transitive vuln netty-handler

### PR DESCRIPTION
**Pull request by datYori**
This dep was causing transitive vuln issue. See JIRA for more details.

This dep is not used anymore anyway

### CODE REVIEW

**Comment by miguelbranco80** [comment]
I'm a bit confused on this one; I assumed we had migrated to v2 of the AWS SDK but apparently we are still on v1?

**Comment by miguelbranco80** [comment]
I thought v2 was used for the AWS package. This is now done (and tested) in Truffle, right, @Alexzerntev ?

**Comment by datYori** [comment]
this one
https://github.com/raw-labs/snapi/blob/main/project/Dependencies.scala#L15
we are using it for the S3 Filesystem package but the one we delete here is not used

**Review by miguelbranco80 — APPROVED** [review]
Understood. So the S3 package uses old v1 (as before) and the AWS package no longer depends on the AWS SDK. Looks ok to me.

**Pull request merged**
