### PR TITLE
RD-10741 Improve error handling in the REST Client.

### PR DESCRIPTION
**Pull request by miguelbranco80**
* Adds new exceptions for bad responses so that messages are clearly defined
* Centralizes automatic retries on 503 in a single method
* Remove accidentally passing bodies as exception messages for auth error

Note that this removes the "fundamentally broken" handleUnexpected method, which is still used by the Runner, so a small fix will be necessary there.

### CODE REVIEW

**Comment by miguelbranco80** [comment]
This needs an addition which is to remove raw.auth altogether - Exceptions and Classes -, since it's not longer necessary!

**Review by torcato — APPROVED** [review]
LGTM

**Pull request closed without merging**
