### PR TITLE
RD-8687 add extra property in lsp for the return type

### PR DESCRIPTION
**Pull request by Alexzerntev**
- Adding return type to LSP
- Alternating the LSP protocol

### CODE REVIEW

**Review by miguelbranco80 — APPROVED** [review]

**Review by datYori — COMMENTED** [review]
not sure my review would be relevant for this change

**Comment by Alexzerntev** [comment]
Branch to be deleted. The branch that will be merged is : https://github.com/raw-labs/snapi/pull/317

**Pull request closed without merging**
